apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJzdk5pa2l0aWo6YzNaT2FXdHBkR2xxT21kcGRHaDFZbDl3WVhSZk1URkJUalZGVUU5Sk1GRjZSSHByUjBVMU9WbFBORjlxVEVGd1MzbEthSGt5V0ZWaU9YaHVOV1ZqVTBJeFFVeFlla055V1d0amFISlFXbmRoTUhCbFNHeENUVEpEUlV4VE5rSnFNWEJaTjJGMFNBPT0iCiAgICAgICAgfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=
type: kubernetes.io/dockerconfigjson
